### PR TITLE
Todos - Main

### PR DESCRIPTION
**Pull request by matej494**

### CODE REVIEW

**Comment by dkulundzic** [comment]
@matej494, why does it say `Merged` for this PR?

**Comment by matej494** [comment]
I don't know. I guess it's some kind of bug. I merged develop into this branch, and it automatically marked it as Merged.

**Comment by matej494** [comment]
Ok, I got it, I accidentally set `todos/main` as base branch, instead of `develop`.

**Comment by dkulundzic** [comment]
Uhm, check the PR branches 😄

**Comment by dkulundzic** [comment]
Yeah.

**Pull request merged**
