### PR TITLE
Todos - Network

### PR DESCRIPTION
**Pull request by matej494**

### CODE REVIEW

**Review by dkulundzic — APPROVED** [review]
Great work! There are no changes to request, I think you did a great job.

One question though: Why do I see project file changes? The `todos` related classes seem to be moved around.

**Comment by matej494** [comment]
@dkulundzic I merged `develop` into `todos/main`, and during resolving conflicts, `Todos` files were removed. I didn't realize it at the moment, so i fixed it pushed it with this commit.

**Comment by dkulundzic** [comment]
@matej494, understood, thanks.

**Comment by matej494** [comment]
Successfully merged branch `todos/network` into branch `todos/main` without conflicts.

**Pull request merged**
