### PR TITLE
Todos - Main

### PR DESCRIPTION
**Pull request by matej494**

### CODE REVIEW

**Review by dkulundzic — APPROVED** [review]
Build properly and seems to work nicely - lets 🚀

**Comment by dkulundzic** [comment]
One question @matej494. I don't see the `completed` Todo state change propagated to the server. Is this planned for later?

**Comment by matej494** [comment]
I planned to implement all `posting` (and `patching`) to the server in the `Todo Form PR` because there is quite a lot of changes in the business logic, so i didn't want to do the same thing twice.

**Comment by dkulundzic** [comment]
@matej494, alright, sounds good.

**Comment by matej494** [comment]
Successfully merged branch `todos/main` into branch `develop` after resolving conflicts.

**Pull request merged**
